workdir: /Users/khash/work/go/src/github.com/cloud66-samples/go-service
steps:
  - step_one:
    name: gobase
    dockerfile: Dockerfile.base
    imagename: gobase
    keep: false
    artefacts:
      - /go/src/app/go-service
  - step_two:
    name: StepTwo
    dockerfile: Dockerfile.main
    imagename: another
    keep: true
