workdir: /Users/khash/work/go/src/github.com/cloud66-samples/go-service
steps:
  - step_one:
    dockerfile: Dockerfile.base
    imagename: gobase
    runtime: false
    artefacts:
      - /some/stuff:/to/some/where
      - /some/where/else:/to/another/place
  - step_two:
    dockerfile: Dockerfile.main
    imagename: another
    runtime: true
